name: ryu-cho

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  ryu-cho:
    name: Ryu Cho
    runs-on: ubuntu-latest
    steps:
      - uses: vuejs-translations/ryu-cho@v1
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          username: github-actions
          email: "action@github.com"
          upstream-repo: https://github.com/rojadesign/vite-docs-de.git
          upstream-repo-branch: main

          head-repo: https://github.com/vitejs/vite
          head-repo-branch: main
          track-from: e6b06e535fb26e064f5c341703df4bcb30aa6432
          path-starts-with: docs/
          workflow-name: ryu-cho
